// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: api/proto/judger.proto

package judger

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JudgeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SourceCode    string                 `protobuf:"bytes,2,opt,name=source_code,json=sourceCode,proto3" json:"source_code,omitempty"`
	Language      string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`                           // "cpp", "go", etc.
	TimeLimit     int64                  `protobuf:"varint,4,opt,name=time_limit,json=timeLimit,proto3" json:"time_limit,omitempty"`       // ms
	MemoryLimit   int64                  `protobuf:"varint,5,opt,name=memory_limit,json=memoryLimit,proto3" json:"memory_limit,omitempty"` // MB
	WorkDir       string                 `protobuf:"bytes,6,opt,name=work_dir,json=workDir,proto3" json:"work_dir,omitempty"`              // 工作目录，如果不传则自动生成
	TestCases     []*TestCase            `protobuf:"bytes,7,rep,name=test_cases,json=testCases,proto3" json:"test_cases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JudgeRequest) Reset() {
	*x = JudgeRequest{}
	mi := &file_api_proto_judger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JudgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JudgeRequest) ProtoMessage() {}

func (x *JudgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_judger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JudgeRequest.ProtoReflect.Descriptor instead.
func (*JudgeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_judger_proto_rawDescGZIP(), []int{0}
}

func (x *JudgeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *JudgeRequest) GetSourceCode() string {
	if x != nil {
		return x.SourceCode
	}
	return ""
}

func (x *JudgeRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *JudgeRequest) GetTimeLimit() int64 {
	if x != nil {
		return x.TimeLimit
	}
	return 0
}

func (x *JudgeRequest) GetMemoryLimit() int64 {
	if x != nil {
		return x.MemoryLimit
	}
	return 0
}

func (x *JudgeRequest) GetWorkDir() string {
	if x != nil {
		return x.WorkDir
	}
	return ""
}

func (x *JudgeRequest) GetTestCases() []*TestCase {
	if x != nil {
		return x.TestCases
	}
	return nil
}

type TestCase struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Input          string                 `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`                                         // 输入内容或文件路径
	ExpectedOutput string                 `protobuf:"bytes,3,opt,name=expected_output,json=expectedOutput,proto3" json:"expected_output,omitempty"` // 预期输出内容或文件路径
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TestCase) Reset() {
	*x = TestCase{}
	mi := &file_api_proto_judger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestCase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestCase) ProtoMessage() {}

func (x *TestCase) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_judger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestCase.ProtoReflect.Descriptor instead.
func (*TestCase) Descriptor() ([]byte, []int) {
	return file_api_proto_judger_proto_rawDescGZIP(), []int{1}
}

func (x *TestCase) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TestCase) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *TestCase) GetExpectedOutput() string {
	if x != nil {
		return x.ExpectedOutput
	}
	return ""
}

type JudgeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // "Accepted", "Wrong Answer", etc.
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	TimeUsed      int64                  `protobuf:"varint,3,opt,name=time_used,json=timeUsed,proto3" json:"time_used,omitempty"`       // ms
	MemoryUsed    int64                  `protobuf:"varint,4,opt,name=memory_used,json=memoryUsed,proto3" json:"memory_used,omitempty"` // KB
	CaseResults   []*CaseResult          `protobuf:"bytes,5,rep,name=case_results,json=caseResults,proto3" json:"case_results,omitempty"`
	CompileLog    string                 `protobuf:"bytes,6,opt,name=compile_log,json=compileLog,proto3" json:"compile_log,omitempty"` // 编译日志
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JudgeResponse) Reset() {
	*x = JudgeResponse{}
	mi := &file_api_proto_judger_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JudgeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JudgeResponse) ProtoMessage() {}

func (x *JudgeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_judger_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JudgeResponse.ProtoReflect.Descriptor instead.
func (*JudgeResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_judger_proto_rawDescGZIP(), []int{2}
}

func (x *JudgeResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *JudgeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *JudgeResponse) GetTimeUsed() int64 {
	if x != nil {
		return x.TimeUsed
	}
	return 0
}

func (x *JudgeResponse) GetMemoryUsed() int64 {
	if x != nil {
		return x.MemoryUsed
	}
	return 0
}

func (x *JudgeResponse) GetCaseResults() []*CaseResult {
	if x != nil {
		return x.CaseResults
	}
	return nil
}

func (x *JudgeResponse) GetCompileLog() string {
	if x != nil {
		return x.CompileLog
	}
	return ""
}

type CaseResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CaseId         string                 `protobuf:"bytes,1,opt,name=case_id,json=caseId,proto3" json:"case_id,omitempty"`
	Status         string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	TimeUsed       int64                  `protobuf:"varint,3,opt,name=time_used,json=timeUsed,proto3" json:"time_used,omitempty"`
	MemoryUsed     int64                  `protobuf:"varint,4,opt,name=memory_used,json=memoryUsed,proto3" json:"memory_used,omitempty"`
	Message        string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Input          string                 `protobuf:"bytes,6,opt,name=input,proto3" json:"input,omitempty"`
	Output         string                 `protobuf:"bytes,7,opt,name=output,proto3" json:"output,omitempty"`
	ExpectedOutput string                 `protobuf:"bytes,8,opt,name=expected_output,json=expectedOutput,proto3" json:"expected_output,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CaseResult) Reset() {
	*x = CaseResult{}
	mi := &file_api_proto_judger_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaseResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaseResult) ProtoMessage() {}

func (x *CaseResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_judger_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaseResult.ProtoReflect.Descriptor instead.
func (*CaseResult) Descriptor() ([]byte, []int) {
	return file_api_proto_judger_proto_rawDescGZIP(), []int{3}
}

func (x *CaseResult) GetCaseId() string {
	if x != nil {
		return x.CaseId
	}
	return ""
}

func (x *CaseResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CaseResult) GetTimeUsed() int64 {
	if x != nil {
		return x.TimeUsed
	}
	return 0
}

func (x *CaseResult) GetMemoryUsed() int64 {
	if x != nil {
		return x.MemoryUsed
	}
	return 0
}

func (x *CaseResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CaseResult) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *CaseResult) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *CaseResult) GetExpectedOutput() string {
	if x != nil {
		return x.ExpectedOutput
	}
	return ""
}

var File_api_proto_judger_proto protoreflect.FileDescriptor

const file_api_proto_judger_proto_rawDesc = "" +
	"\n" +
	"\x16api/proto/judger.proto\x12\x06judger\"\xe9\x01\n" +
	"\fJudgeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vsource_code\x18\x02 \x01(\tR\n" +
	"sourceCode\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\x12\x1d\n" +
	"\n" +
	"time_limit\x18\x04 \x01(\x03R\ttimeLimit\x12!\n" +
	"\fmemory_limit\x18\x05 \x01(\x03R\vmemoryLimit\x12\x19\n" +
	"\bwork_dir\x18\x06 \x01(\tR\aworkDir\x12/\n" +
	"\n" +
	"test_cases\x18\a \x03(\v2\x10.judger.TestCaseR\ttestCases\"Y\n" +
	"\bTestCase\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05input\x18\x02 \x01(\tR\x05input\x12'\n" +
	"\x0fexpected_output\x18\x03 \x01(\tR\x0eexpectedOutput\"\xd7\x01\n" +
	"\rJudgeResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1b\n" +
	"\ttime_used\x18\x03 \x01(\x03R\btimeUsed\x12\x1f\n" +
	"\vmemory_used\x18\x04 \x01(\x03R\n" +
	"memoryUsed\x125\n" +
	"\fcase_results\x18\x05 \x03(\v2\x12.judger.CaseResultR\vcaseResults\x12\x1f\n" +
	"\vcompile_log\x18\x06 \x01(\tR\n" +
	"compileLog\"\xec\x01\n" +
	"\n" +
	"CaseResult\x12\x17\n" +
	"\acase_id\x18\x01 \x01(\tR\x06caseId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1b\n" +
	"\ttime_used\x18\x03 \x01(\x03R\btimeUsed\x12\x1f\n" +
	"\vmemory_used\x18\x04 \x01(\x03R\n" +
	"memoryUsed\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12\x14\n" +
	"\x05input\x18\x06 \x01(\tR\x05input\x12\x16\n" +
	"\x06output\x18\a \x01(\tR\x06output\x12'\n" +
	"\x0fexpected_output\x18\b \x01(\tR\x0eexpectedOutput2D\n" +
	"\fJudgeService\x124\n" +
	"\x05Judge\x12\x14.judger.JudgeRequest\x1a\x15.judger.JudgeResponseB+Z)github.com/FashOJ/Judger/api/proto/judgerb\x06proto3"

var (
	file_api_proto_judger_proto_rawDescOnce sync.Once
	file_api_proto_judger_proto_rawDescData []byte
)

func file_api_proto_judger_proto_rawDescGZIP() []byte {
	file_api_proto_judger_proto_rawDescOnce.Do(func() {
		file_api_proto_judger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_judger_proto_rawDesc), len(file_api_proto_judger_proto_rawDesc)))
	})
	return file_api_proto_judger_proto_rawDescData
}

var file_api_proto_judger_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_proto_judger_proto_goTypes = []any{
	(*JudgeRequest)(nil),  // 0: judger.JudgeRequest
	(*TestCase)(nil),      // 1: judger.TestCase
	(*JudgeResponse)(nil), // 2: judger.JudgeResponse
	(*CaseResult)(nil),    // 3: judger.CaseResult
}
var file_api_proto_judger_proto_depIdxs = []int32{
	1, // 0: judger.JudgeRequest.test_cases:type_name -> judger.TestCase
	3, // 1: judger.JudgeResponse.case_results:type_name -> judger.CaseResult
	0, // 2: judger.JudgeService.Judge:input_type -> judger.JudgeRequest
	2, // 3: judger.JudgeService.Judge:output_type -> judger.JudgeResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_proto_judger_proto_init() }
func file_api_proto_judger_proto_init() {
	if File_api_proto_judger_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_judger_proto_rawDesc), len(file_api_proto_judger_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_judger_proto_goTypes,
		DependencyIndexes: file_api_proto_judger_proto_depIdxs,
		MessageInfos:      file_api_proto_judger_proto_msgTypes,
	}.Build()
	File_api_proto_judger_proto = out.File
	file_api_proto_judger_proto_goTypes = nil
	file_api_proto_judger_proto_depIdxs = nil
}
